from typing import List, Optional, Tuple
import tree_sitter

from app.parser.models import (
    CodeLocation,
    ImportStatement,
    ImportItem,
    FunctionDef,
    ClassDef,
    CallSite,
)
from app.parser.complexity import compute_node_cyclomatic_complexity


class JavaScriptAstVisitor:
    """
    Traverses JavaScript & TypeScript ASTs generated by Tree-sitter to extract
    imports, classes, functions, methods, calls, and structural metrics.

    Uses an explicit stack-based (iterative) traversal to avoid Windows
    access-violation crashes from dangling tree_sitter.Node C-pointers.
    Text is always extracted via source_bytes byte-slicing.
    """

    def __init__(self, module_id: str, source_bytes: bytes):
        self.module_id = module_id
        self.source_bytes = source_bytes

        self.imports: List[ImportStatement] = []
        self.classes: List[ClassDef] = []
        self.functions: List[FunctionDef] = []
        self.calls: List[CallSite] = []

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _text(self, node: tree_sitter.Node) -> str:
        if not node:
            return ""
        try:
            return self.source_bytes[node.start_byte:node.end_byte].decode(
                "utf-8", errors="ignore"
            )
        except Exception:
            return ""

    def _loc(self, node: tree_sitter.Node) -> CodeLocation:
        return CodeLocation(
            start_line=node.start_point[0] + 1,
            start_col=node.start_point[1] + 1,
            end_line=node.end_point[0] + 1,
            end_col=node.end_point[1] + 1,
        )

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def visit(self, root_node: tree_sitter.Node):
        """
        Iterative DFS.  Stack entries: (node, curr_class, curr_func).
        """
        stack: List[Tuple] = [(root_node, None, None)]

        while stack:
            node, curr_class, curr_func = stack.pop()
            ntype = node.type

            if ntype == "import_statement":
                self._handle_import_statement(node)
                continue

            elif node.is_named and ntype in ("class_declaration", "class", "class_expression"):
                cls_def = self._handle_class(node)
                if cls_def:
                    for child in reversed(node.children):
                        stack.append((child, cls_def, curr_func))
                continue

            elif node.is_named and ntype in ("function_declaration", "function", "function_expression"):
                fn_def = self._handle_function(node, curr_class, curr_func)
                if fn_def:
                    body = node.child_by_field_name("body")
                    if body:
                        for child in reversed(body.children):
                            stack.append((child, curr_class, fn_def))
                continue

            elif ntype == "method_definition":
                fn_def = self._handle_method(node, curr_class)
                if fn_def:
                    if curr_class:
                        curr_class.methods.append(fn_def.id)
                    body = node.child_by_field_name("body")
                    if body:
                        for child in reversed(body.children):
                            stack.append((child, curr_class, fn_def))
                continue

            elif ntype == "call_expression":
                self._handle_call(node, curr_class, curr_func)
                # fall through to push children (for nested calls)

            for child in reversed(node.children):
                stack.append((child, curr_class, curr_func))

        # Compute WMC for classes
        for cls_def in self.classes:
            cls_def.wmc = sum(
                fn.cyclomatic_complexity
                for fn in self.functions
                if fn.parent_class == cls_def.id
            )

    # ------------------------------------------------------------------
    # Node handlers
    # ------------------------------------------------------------------

    def _handle_import_statement(self, node: tree_sitter.Node):
        """Handle ES module import statements."""
        source = ""
        is_relative = False
        items: List[ImportItem] = []

        source_node = node.child_by_field_name("source")
        if source_node:
            raw_source = self._text(source_node).strip("'\"`")
            source = raw_source
            is_relative = raw_source.startswith(".")

        for child in node.children:
            if child.type == "import_clause":
                for item in child.children:
                    if item.type == "identifier":
                        items.append(ImportItem(name=self._text(item)))
                    elif item.type == "named_imports":
                        for specifier in item.children:
                            if specifier.type == "import_specifier":
                                name_node = specifier.child_by_field_name("name")
                                if not name_node and specifier.children:
                                    name_node = specifier.children[0]
                                alias_node = specifier.child_by_field_name("alias")
                                if not alias_node and len(specifier.children) > 2:
                                    alias_node = specifier.children[-1]
                                items.append(
                                    ImportItem(
                                        name=self._text(name_node) if name_node else "",
                                        alias=self._text(alias_node) if alias_node else None,
                                    )
                                )
                    elif item.type == "namespace_import":
                        alias_node = item.child_by_field_name("alias")
                        if not alias_node and len(item.children) > 1:
                            alias_node = item.children[-1]
                        items.append(
                            ImportItem(
                                name="*",
                                alias=self._text(alias_node) if alias_node else None,
                            )
                        )

        self.imports.append(
            ImportStatement(
                source=source,
                items=items,
                is_relative=is_relative,
                relative_level=source.count("../") + (1 if source.startswith("./") else 0),
                location=self._loc(node),
            )
        )

    def _handle_class(self, node: tree_sitter.Node) -> Optional[ClassDef]:
        name_node = node.child_by_field_name("name")
        class_name = self._text(name_node) if name_node else "AnonymousClass"
        class_id = f"{self.module_id}::{class_name}"

        base_classes: List[str] = []
        interfaces: List[str] = []

        for child in node.children:
            if child.type == "class_heritage":
                in_implements = False
                for h_child in child.children:
                    if h_child.type == "extends":
                        in_implements = False
                    elif h_child.type == "implements":
                        in_implements = True
                    elif h_child.type in ("identifier", "type_identifier", "member_expression"):
                        if in_implements:
                            interfaces.append(self._text(h_child))
                        else:
                            base_classes.append(self._text(h_child))

        loc_lines = (node.end_point[0] - node.start_point[0]) + 1
        cls_def = ClassDef(
            id=class_id,
            name=class_name,
            base_classes=base_classes,
            interfaces=interfaces,
            loc=loc_lines,
            location=self._loc(node),
        )
        self.classes.append(cls_def)
        return cls_def

    def _handle_method(
        self, node: tree_sitter.Node, curr_class: Optional[ClassDef]
    ) -> Optional[FunctionDef]:
        name_node = node.child_by_field_name("name")
        method_name = self._text(name_node) if name_node else "anonymousMethod"
        parent_class_id = curr_class.id if curr_class else self.module_id
        func_id = f"{parent_class_id}.{method_name}"

        parameters: List[str] = []
        params_node = node.child_by_field_name("parameters")
        if params_node:
            for p in params_node.children:
                if p.type in ("identifier", "required_parameter"):
                    parameters.append(self._text(p))

        cc = compute_node_cyclomatic_complexity(
            node, language="javascript", source_bytes=self.source_bytes
        )
        loc_lines = (node.end_point[0] - node.start_point[0]) + 1

        fn_def = FunctionDef(
            id=func_id,
            name=method_name,
            is_method=True,
            parent_class=parent_class_id,
            parameters=parameters,
            cyclomatic_complexity=cc,
            loc=loc_lines,
            location=self._loc(node),
        )
        self.functions.append(fn_def)
        return fn_def

    def _handle_function(
        self,
        node: tree_sitter.Node,
        curr_class: Optional[ClassDef],
        curr_func: Optional[FunctionDef],
    ) -> Optional[FunctionDef]:
        name_node = node.child_by_field_name("name")
        func_name = self._text(name_node) if name_node else "anonymousFunction"
        func_id = f"{self.module_id}::{func_name}"

        parameters: List[str] = []
        params_node = node.child_by_field_name("parameters")
        if params_node:
            for p in params_node.children:
                if p.type in ("identifier",):
                    parameters.append(self._text(p))

        cc = compute_node_cyclomatic_complexity(
            node, language="javascript", source_bytes=self.source_bytes
        )
        loc_lines = (node.end_point[0] - node.start_point[0]) + 1

        fn_def = FunctionDef(
            id=func_id,
            name=func_name,
            is_method=False,
            parameters=parameters,
            cyclomatic_complexity=cc,
            loc=loc_lines,
            location=self._loc(node),
        )
        self.functions.append(fn_def)
        return fn_def

    def _handle_call(
        self,
        node: tree_sitter.Node,
        curr_class: Optional[ClassDef],
        curr_func: Optional[FunctionDef],
    ):
        func_node = node.child_by_field_name("function")
        if not func_node and node.children:
            func_node = node.children[0]
        if not func_node:
            return

        callee_name = self._text(func_node)
        if not callee_name:
            return

        caller_id = (
            curr_func.id
            if curr_func
            else (curr_class.id if curr_class else self.module_id)
        )
        self.calls.append(
            CallSite(
                caller_id=caller_id,
                callee_name=callee_name,
                location=self._loc(node),
            )
        )
