from typing import List, Optional, Tuple
import tree_sitter

from app.parser.models import (
    CodeLocation,
    ImportStatement,
    ImportItem,
    FunctionDef,
    ClassDef,
    CallSite,
)
from app.parser.complexity import compute_node_cyclomatic_complexity


class PythonAstVisitor:
    """
    Traverses Python ASTs generated by Tree-sitter to extract imports,
    classes, functions, method hierarchies, calls, and structural metrics.

    Uses an explicit stack-based (iterative) traversal to avoid Windows
    access-violation crashes caused by dangling C-pointers in recursive
    tree_sitter.Node references.  Text is always extracted via byte-slicing
    (source_bytes[node.start_byte:node.end_byte]) rather than node.text.
    """

    def __init__(self, module_id: str, source_bytes: bytes):
        self.module_id = module_id
        self.source_bytes = source_bytes

        self.imports: List[ImportStatement] = []
        self.classes: List[ClassDef] = []
        self.functions: List[FunctionDef] = []
        self.calls: List[CallSite] = []

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _text(self, node: tree_sitter.Node) -> str:
        """Safe byte-slice text extraction — never crashes on Windows."""
        if node is None:
            return ""
        try:
            return self.source_bytes[node.start_byte:node.end_byte].decode(
                "utf-8", errors="ignore"
            )
        except Exception:
            return ""

    def _loc(self, node: tree_sitter.Node) -> CodeLocation:
        return CodeLocation(
            start_line=node.start_point[0] + 1,
            start_col=node.start_point[1] + 1,
            end_line=node.end_point[0] + 1,
            end_col=node.end_point[1] + 1,
        )

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def visit(self, root_node: tree_sitter.Node):
        """
        Iterative DFS over the AST.  The stack holds tuples of
        (node, current_class_def, current_function_def).
        """
        # Stack entries: (node, curr_class, curr_func)
        stack: List[Tuple] = [(root_node, None, None)]

        while stack:
            node, curr_class, curr_func = stack.pop()
            ntype = node.type

            # -- fast skip for leaf/non-structural nodes --
            if ntype in ("comment", "escape_sequence"):
                continue

            if ntype == "import_statement":
                self._handle_import_statement(node)
                continue  # no children needed

            elif ntype == "import_from_statement":
                self._handle_import_from_statement(node)
                continue

            elif ntype == "class_definition":
                cls_def = self._handle_class_definition(node)
                if cls_def:
                    # Push children with updated context (reversed for LIFO order)
                    for child in reversed(node.children):
                        stack.append((child, cls_def, curr_func))
                continue

            elif ntype == "function_definition":
                fn_def = self._handle_function_definition(node, curr_class, curr_func)
                if fn_def:
                    if curr_class:
                        curr_class.methods.append(fn_def.id)
                    # Push body children for further traversal
                    body = node.child_by_field_name("body")
                    if not body:
                        for c in node.children:
                            if c.type == "block":
                                body = c
                                break
                    if body:
                        for child in reversed(body.children):
                            stack.append((child, curr_class, fn_def))
                continue

            elif ntype == "call":
                self._handle_call(node, curr_class, curr_func)
                # fall through to push children (for nested calls)

            # Push all children with inherited context
            for child in reversed(node.children):
                stack.append((child, curr_class, curr_func))

        # Compute WMC for every class after full traversal
        for cls_def in self.classes:
            cls_def.wmc = sum(
                fn.cyclomatic_complexity
                for fn in self.functions
                if fn.parent_class == cls_def.id
            )

    # ------------------------------------------------------------------
    # Node handlers — all use self._text() for safe extraction
    # ------------------------------------------------------------------

    def _handle_import_statement(self, node: tree_sitter.Node):
        """Handle: import math  /  import os.path as osp"""
        for child in node.children:
            if child.type == "dotted_name":
                source = self._text(child)
                self.imports.append(
                    ImportStatement(
                        source=source,
                        items=[ImportItem(name=source)],
                        is_relative=False,
                        relative_level=0,
                        location=self._loc(node),
                    )
                )
            elif child.type == "aliased_import":
                name_node = child.child_by_field_name("name")
                if not name_node and child.children:
                    name_node = child.children[0]
                alias_node = child.child_by_field_name("alias")
                if not alias_node and len(child.children) > 1:
                    alias_node = child.children[-1]
                if name_node:
                    source = self._text(name_node)
                    alias = self._text(alias_node) if alias_node else None
                    self.imports.append(
                        ImportStatement(
                            source=source,
                            items=[ImportItem(name=source, alias=alias)],
                            is_relative=False,
                            relative_level=0,
                            location=self._loc(node),
                        )
                    )

    def _handle_import_from_statement(self, node: tree_sitter.Node):
        """Handle: from .utils import helper as h  /  from os import path"""
        source = ""
        is_relative = False
        relative_level = 0
        items: List[ImportItem] = []
        is_after_import_kw = False

        for child in node.children:
            ctype = child.type
            if ctype == "from":
                continue
            elif ctype == "import":
                is_after_import_kw = True
                continue

            if not is_after_import_kw:
                if ctype == "relative_import":
                    is_relative = True
                    for sub in child.children:
                        if sub.type == "import_prefix":
                            relative_level = len(self._text(sub))
                        elif sub.type == "dotted_name":
                            source = self._text(sub)
                elif ctype == "dotted_name":
                    source = self._text(child)
            else:
                if ctype == "dotted_name":
                    items.append(ImportItem(name=self._text(child)))
                elif ctype == "aliased_import":
                    name_node = child.child_by_field_name("name")
                    if not name_node and child.children:
                        name_node = child.children[0]
                    alias_node = child.child_by_field_name("alias")
                    if not alias_node and len(child.children) > 1:
                        alias_node = child.children[-1]
                    items.append(
                        ImportItem(
                            name=self._text(name_node) if name_node else "",
                            alias=self._text(alias_node) if alias_node else None,
                        )
                    )
                elif ctype in ("wildcard_import", "*"):
                    items.append(ImportItem(name="*"))

        self.imports.append(
            ImportStatement(
                source=source,
                items=items,
                is_relative=is_relative,
                relative_level=relative_level,
                location=self._loc(node),
            )
        )

    def _handle_class_definition(
        self, node: tree_sitter.Node
    ) -> Optional[ClassDef]:
        """Extract ClassDef metadata; does NOT recurse — caller pushes children."""
        # Find class name
        class_name = "AnonymousClass"
        for child in node.children:
            if child.type == "identifier":
                class_name = self._text(child)
                break

        class_id = f"{self.module_id}::{class_name}"

        # Base classes (argument_list node or superclasses field)
        base_classes: List[str] = []
        for child in node.children:
            if child.type == "argument_list":
                for arg in child.children:
                    if arg.type in ("identifier", "attribute"):
                        base_classes.append(self._text(arg))
                break

        loc_lines = (node.end_point[0] - node.start_point[0]) + 1

        cls_def = ClassDef(
            id=class_id,
            name=class_name,
            base_classes=base_classes,
            loc=loc_lines,
            location=self._loc(node),
        )
        self.classes.append(cls_def)
        return cls_def

    def _handle_function_definition(
        self,
        node: tree_sitter.Node,
        curr_class: Optional[ClassDef],
        curr_func: Optional[FunctionDef],
    ) -> Optional[FunctionDef]:
        """Extract FunctionDef metadata; does NOT recurse — caller pushes body."""
        # Find function name
        func_name = "anonymous_func"
        for child in node.children:
            if child.type == "identifier":
                func_name = self._text(child)
                break

        func_id = (
            f"{curr_class.id}.{func_name}"
            if curr_class
            else f"{self.module_id}::{func_name}"
        )
        parent_class_id = curr_class.id if curr_class else None
        is_method = curr_class is not None

        # Visibility
        is_private = func_name.startswith("_") and not (
            func_name.startswith("__") and func_name.endswith("__")
        )
        visibility = "private" if is_private else "public"

        # Parameters
        parameters: List[str] = []
        params_node = node.child_by_field_name("parameters")
        if not params_node:
            for child in node.children:
                if child.type == "parameters":
                    params_node = child
                    break
        if params_node:
            for p in params_node.children:
                if p.type in (
                    "identifier",
                    "typed_parameter",
                    "default_parameter",
                    "typed_default_parameter",
                ):
                    param_ident = p.child_by_field_name("name") or p
                    raw = self._text(param_ident).split(":")[0].split("=")[0].strip()
                    if raw and raw not in ("self", "cls"):
                        parameters.append(raw)

        # Return type annotation
        return_type: Optional[str] = None
        rt_node = node.child_by_field_name("return_type")
        if rt_node:
            return_type = self._text(rt_node)

        # Complexity & size
        cc = compute_node_cyclomatic_complexity(
            node, language="python", source_bytes=self.source_bytes
        )
        loc_lines = (node.end_point[0] - node.start_point[0]) + 1

        fn_def = FunctionDef(
            id=func_id,
            name=func_name,
            is_method=is_method,
            parent_class=parent_class_id,
            visibility=visibility,
            parameters=parameters,
            return_type=return_type,
            cyclomatic_complexity=cc,
            loc=loc_lines,
            location=self._loc(node),
        )
        self.functions.append(fn_def)
        return fn_def

    def _handle_call(
        self,
        node: tree_sitter.Node,
        curr_class: Optional[ClassDef],
        curr_func: Optional[FunctionDef],
    ):
        """Record a call site."""
        func_node = node.child_by_field_name("function")
        if not func_node and node.children:
            func_node = node.children[0]
        if not func_node:
            return

        callee_name = self._text(func_node)
        if not callee_name:
            return

        caller_id = (
            curr_func.id
            if curr_func
            else (curr_class.id if curr_class else self.module_id)
        )
        self.calls.append(
            CallSite(
                caller_id=caller_id,
                callee_name=callee_name,
                location=self._loc(node),
            )
        )
